import { createCrudService } from '@/lib/createCrudService'

export const professionalsService = createCrudService('professionals')
export const initialAssessmentsService = createCrudService('initial_assessments')
export const careCyclesService = createCrudService('care_cycles')
export const careSessionsService = createCrudService('care_sessions')
export const treatmentPausesService = createCrudService('treatment_pauses')
export const medicalRecordsService = createCrudService('medical_records')
export const chargesService = createCrudService('charges')
export const transfersService = createCrudService('transfers')
export const transferQueueService = createCrudService('transfer_queue')
export const demandsService = createCrudService('demands')
export const demandResponsesService = createCrudService('demand_responses')
export const profilesService = createCrudService('profiles')
export const internalExpensesService = createCrudService('internal_expenses')
export const supportTicketsService = createCrudService('support_tickets')
export const legalTermsService = createCrudService('legal_terms')
export const contractTemplatesService = createCrudService('contract_templates')
export const pricingVersionsService = createCrudService('pricing_matrix_versions')
export const pricingEntriesService = createCrudService('pricing_matrix_entries')
export const npsSurveysService = createCrudService('nps_surveys')
export const notificationsService = createCrudService('notifications')
export const contractsService = createCrudService('contracts')
export const professionalInvoicesService = createCrudService('professional_invoices')
export const delumaExportsService = createCrudService('deluma_exports')
export const lgpdRequestsService = createCrudService('lgpd_requests')
